const breadcrumbNameMap = {
  '/userManager': '用户信息',
  '/classroomManager/classroomList': '教室列表',
  '/classroomManager/classroomType': '教室类型',
  '/maintenanceManager': '维修管理',
  '/workorderManage/workOrderInformation':'维修人员信息',
  '/workorderManage/workOrderManager':'工单管理',
  '/workorderManage/workOrderType':'工单类型',
  '/workorderManage/timeOut':'超时配置',
  '/workorderManage/type':'工单类型',
  '/workorderManage/grade':'分数统计',
  '/sys_manager/nodeManager':'节点管理',
  '/sys_manager/adminManager':'管理员管理',
  '/adviceFeedback':'反馈记录',
  '/sys_manager/role':'角色管理',
  '/sys_manager/log':'日志管理',
  '/sys_manager/databaseBackup':'数据库备份',
  '/equipmentManager/equipmentInformation':'设备基本信息',
  '/equipmentManager/equipmentType':'设备分类',
  '/maintenanceDay/maintenanceRecord':'维护记录',
  '/maintenanceDay/maintenanceType':'维护任务',
  '/maintenanceDay/manualMaintenanceType':'定期维护配置',
  '/networkingManager/information':'联网设备基本信息',
  '/networkingManager/type':'联网设备分类',
  '/networkingManager/switchToRecord':'开关记录',
  '/warningManagement':'预警管理',
  '/materialManager/materialManager':'物料管理',
  '/materialManager/come':'物料出库',
  '/materialManager/storage':'物料入库',
  '/materialManager/role':'角色配置',
  '/materialManager/material':'物料配置',
  '/slideshow':'轮播图管理',
  '/mobileModule':'手机端模块管理',
  '/mobileRole':'手机端角色管理',
  '/depManager':'院系管理',
  '/factoryManagement':'厂家管理',
  '/statisticalManager/workStatistics':'维修工单统计',
  '/statisticalManager/dataStatistics':'其他统计',
};
  
module.exports = breadcrumbNameMap;